### ISSUE TITLE
Default Magento 2.4.3-p1 demo store with sample data, Hyva 1.1.9. console errors Alpine

### ISSUE THREAD

**Issue by DHSServices** [ProxiBlue/hyva-proxiblue-multimenu#2] opened 2022-01-07 15:39 UTC
We get console errors and the multimenu is not working on mobile and malfunctions on desktop mode (submenu hover doesn't show level 3 menu). See attachment.
![m243p1_hyva119_multimenu_console-errors](https://user-images.githubusercontent.com/70269551/148567804-1992ce86-ac4f-4aff-a6ea-3aac6e9cbe90.JPG)
.

**Comment by ProxiBlue** [comment] 2022-01-07 16:27
Is this in a clean 1.1.9 install on m2.4.3 ?

**Comment by DHSServices** [comment] 2022-01-07 16:46
Yes it is, but m2.4.3-p1
![hyva-version](https://user-images.githubusercontent.com/70269551/148577200-c4a3aaf1-1d85-4313-a137-50a64267cc65.JPG)
.

**Comment by ProxiBlue** [comment] 2022-01-07 16:53
Thanks. Will do a clean install and see if i can reproduce.

**Comment by ProxiBlue** [comment] 2022-01-08 00:58
Hello, I can reproduce this issue on a clean 2.4.3-p1 and clean 1.1.9 install.

![image](https://user-images.githubusercontent.com/4994260/148624867-05477bc9-4e15-4976-9cfb-0663179bb760.png)

The fact it works in my upgraded 1.1.9 is likely due to custom theme files in site theme.

I will produce an update to make this compatible again

**Comment by ProxiBlue** [comment] 2022-01-08 01:40
Ok, so the reason this still works in my upgraded 1.1.9, is due to custom theme, and placement of header.phtml, which instantiates the menu object via alpine

![image](https://user-images.githubusercontent.com/4994260/148626551-2127354c-4eb5-4cc9-8d3d-a5e877a46a29.png)

**Comment by ProxiBlue** [comment] 2022-01-08 06:05
Hello,

I have updated the code to make a new release 1.3.0 that is compatible with hyva 1.1.9 and teh split menu files.
Please update, ensuring you get version 1.3.x range of the module



https://user-images.githubusercontent.com/4994260/148633613-b7edf3ce-cac2-4afa-a66b-9a01484a67cb.mp4

**Comment by DHSServices** [comment] 2022-01-10 14:57
Works like a charm! Thank you very much.

**Comment by ProxiBlue** [comment] 2022-01-10 23:46
Great, I will close this ticket then.

PS: you will see an improvement I had done (over standard hyva menus) is that the menu is not populated 2 x in the DOM (which can be huge)
The menu data is copied between mobile and desktop menu containers when required, so it only occupies one section at a time, thus making for a lot smaller page load size.

**Closed as completed by ProxiBlue** 2022-01-10 23:46 UTC
