### ISSUE TITLE
tailwind run build-prod breaks mobile menu

### ISSUE THREAD

**Issue by DHSServices** [ProxiBlue/hyva-proxiblue-multimenu#4] opened 2022-01-24 13:17 UTC
If we do a Tailwind "npm run built-prod" with the multi-menu phtml files in our own custom theme, the mobile menu doesn't work properly anymore.
Also if we add the /vendor/proxi-blue/ directory to the tailwind.config.js for purging a build production it breaks the mobile menu.
Just running with the build-dev the multi-menu works okay.
It seems if we remove from desktop.phtml this class on line 43:  class="group group-<?= /* @noEscape */ (string)$index ?>"
The mobile view works okay (after built-prod), but the desktop view is then not working right.
Any idea?
![npm-build-prod-breaks-mobile](https://user-images.githubusercontent.com/70269551/150789491-b636257c-55ca-4929-8d62-1789b7345f65.gif)

**Comment by ProxiBlue** [comment] 2022-01-24 15:50
Can you attach your tailwind config.

I cannot reproduce. Run build prod fine on a site.

**Comment by DHSServices** [comment] 2022-01-24 20:33
This is the purging part I use in the tailwind.config.js of our custom theme:
`
        content: [
            // this theme's phtml files
            '../../**/*.phtml',
            // parent theme in Vendor (if this is a child-theme)
            '../../../../../../../vendor/hyva-themes/magento2-default-theme/**/*.phtml',
            '../../../../../../../vendor/proxi-blue/multi-menu/**/*.phtml',
            // app/code phtml files (if need tailwind classes from app/code modules)
            //'../../../../../../../app/code/**/*.phtml',
`
The strange thing is the desktop.phtml breaks the mobile view?

**Comment by ProxiBlue** [comment] 2022-01-24 21:46
Any way i can get access to the frontend of that build?

**Comment by DHSServices** [comment] 2022-01-24 22:12
Unfortunately it is a staging with IP block, and I am still testing locally myself.

**Comment by ProxiBlue** [comment] 2022-01-25 02:23
I do have a fixed ip


[image: proxiblue_document_header.png]

http://www.proxiblue.com.au

Quality, not Quantity!

**Comment by DHSServices** [comment] 2022-01-25 14:22
You can take a look at the broken Mobile view here: 

The only thing I did was:
1. Install proxiblue-multimenu
2. Copy: \view\frontend\templates\html\header\menuview\desktop.phtml
3. With no changes to my custom theme in: \app\design\frontend\Custom\Theme\ProxiBlue_MultiMenu\templates\html\header\menu\desktop.phtml
4. Do a "npm run built-prod"
5. Run bin/magento setup:upgrade

Suspected CSS?
![image](https://user-images.githubusercontent.com/70269551/150993748-e094698e-1955-4a6d-af59-c1a73124d4c0.png)
My (renamed) tailwind-output.css:
[tailwind-output.txt](https://github.com/ProxiBlue/hyva-proxiblue-multimenu/files/7934261/tailwind-output.txt)

**Comment by DHSServices** [comment] 2022-01-25 15:16
I am pretty sure it is this group CSS
`.group:hover .group-hover\:scale-100 {
	--tw-scale-x: 1;
	--tw-scale-y: 1;
	transform: var(--tw-transform);
}`
When I remove it from the styles.css the mobile view works perfect. Only the desktop view then breaks.

**Comment by DHSServices** [comment] 2022-01-25 16:27
Changing desktop.html line 70 solves the issue:
Old: `->setData('child_css', 'border-t-0 transform scale-0 group-hover:scale-100 origin-top')`
New: `->setData('child_css', 'border-t-0 transform lg:scale-0 lg:group-hover:scale-100 origin-top')`

**Comment by ProxiBlue** [comment] 2022-01-25 23:40
Great find, I will make that change, and push an update.

**Comment by ProxiBlue** [comment] 2022-01-25 23:48
mmm, that causes an issue for me on a clean hyva and 2.4.3 install.
The desktop menus start expenaded

![image](https://user-images.githubusercontent.com/4994260/151078881-2a0c3256-082d-4ab5-85df-b7cf52cfac09.png)

**Comment by ProxiBlue** [comment] 2022-01-26 00:22
Ok, I can now reproduce your issue, with no need to copy the desktop.phtml to custom theme.

![image](https://user-images.githubusercontent.com/4994260/151081880-331f09aa-9aed-4336-9147-7fc11a6ac15c.png)

**Comment by ProxiBlue** [comment] 2022-01-26 01:23
actually, no, that is not the same issue, this was caused by an unreleased version change I had made to desktop-pull-right adjustments

**Comment by ProxiBlue** [comment] 2022-01-26 02:59
Ok, so I simply cannot reproduce this issue

I am using a clean m2.4.3-p1 + hyva 1.1.10

![image](https://user-images.githubusercontent.com/4994260/151096178-88d32881-23a2-4cc2-a81f-18ac88ca05d3.png)

I have created a child theme, and copied the desktop.phtml as per your guide:

![image](https://user-images.githubusercontent.com/4994260/151096257-5fa98f9b-4e16-4613-afe7-a84e4797ad45.png)

The theme is setup in admin, and via breakpoints, I can confirm the theme desktop.phtml file is in use

![image](https://user-images.githubusercontent.com/4994260/151096392-12319b2a-00f9-457e-b30c-64922c6eff50.png)

![image](https://user-images.githubusercontent.com/4994260/151096477-59c91d27-be6c-4e16-a9ae-45077c88b74d.png)

I built tailwind prod:

```
02:49 $ npm run build-prod

> tailwind@1.0.0 build-prod /vagrant/sites/test243/app/design/frontend/Custom/theme/web/tailwind
> NODE_ENV=production TAILWIND_COMPILE_MODE=jit npm run build && npm run minify && npm run output-success


> tailwind@1.0.0 build /vagrant/sites/test243/app/design/frontend/Custom/theme/web/tailwind
> npx postcss tailwind-source.css -o tailwind-output.css

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.

> tailwind@1.0.0 minify /vagrant/sites/test243/app/design/frontend/Custom/theme/web/tailwind
> npx csso tailwind-output.css --output ../css/styles.css


> tailwind@1.0.0 output-success /vagrant/sites/test243/app/design/frontend/Custom/theme/web/tailwind
> echo "\033[0;32mDone!\033[0m"

Done!
✔ /vagrant/sites/test243/app/design/frontend/Custom/theme/web/tailwind [master L|●40✚ 5…1] 

```

Menu works as expected


https://user-images.githubusercontent.com/4994260/151096659-3e23aa34-479f-40f8-b209-66f0589a2888.mp4

my tailwind config is as such:

```
purge: {
        // Examples for excluding patterns from purge
        // options: {
        //     safelist: [/^bg-opacity-/, /^-?[mp][trblxy]?-[4,8]$/, /^text-shadow/],
        // },
        content: [
            // this theme's phtml files
            '../../**/*.phtml',
            // parent theme in Vendor (if this is a child-theme)
            '../../../../../../../vendor/hyva-themes/magento2-default-theme/**/*.phtml',
            // app/code phtml files (if need tailwind classes from app/code modules)
            '../../../../../../../app/code/**/*.phtml',
            // react app src files (if Hyvä Checkout is installed in app/code)
            //'../../../../../../../app/code/**/src/**/*.jsx',
            // react app src files in vendor (If Hyvä Checkout is installed in vendor)
            //'../../../../../../../vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src/**/*.jsx',
            //'../../../../../../../vendor/hyva-themes/magento2-hyva-checkout/src/view/frontend/templates/react-container.phtml',
            // widget block classes from app/code
            '../../../../../../../app/code/**/Block/Widget/**/*.php'
        ]
    }
```

**Comment by ProxiBlue** [comment] 2022-01-26 03:01
The site you gave, menus seem to be working? (maybe because of your changes?)

![image](https://user-images.githubusercontent.com/4994260/151096849-2caa3325-4bfe-4e56-872c-e0b001d30996.png)

I did release a new version for some other updates.

Some styling twekas on mobile menu child pullout width, desktop pull-left calculations fix

**Comment by ProxiBlue** [comment] 2022-01-26 03:07
try v 1.3.6, I did make an improvement in the js code, where the slide-to-left calculation are now bypassed when on mobile (no need for that)

In my original thought that I had reproduced your issue, the styles injected by the slide-to-left caused mobile menus to be hidden.

Possible the same issue is involved?

**Comment by DHSServices** [comment] 2022-01-26 10:49
Hi Lucas, I changed the staging site allready before you checked it.
I've tried a clean install m2.4.3-p1+hyva1.1.10 with v 1.3.6 and keep getting the issue in a custom theme build prod.
Could be the issue only exists in Chrome? Don't know which browser you checked, because Firefox doesn't seem to have this problem.
As soon as I edit the desktop.phtml and do a build prod, the issue is solved.
So I have no problem any more, will solve this in our custom theme desktop.phtml.

**Comment by ProxiBlue** [comment] 2022-01-26 10:55
Very strange, I have tried.

I hate not knowing why, as something is different (and we both used clean installs)

I will close this for now, but will keep my eye on it and try periodically as I do new builds

**Closed as completed by ProxiBlue** 2022-01-26 10:55 UTC

**Comment by DHSServices** [comment] 2022-01-26 10:57
Added this: 
Could be the issue only exists in Chrome? Don't know which browser you checked, because Firefox doesn't seem to have this problem.

**Comment by ProxiBlue** [comment] 2022-01-26 10:57
> Could be the issue only exists in Chrome? Don't know which browser you checked, because Firefox doesn't seem to have this problem.

Ah, very good point. I am using chrome, on Ubuntu: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by DHSServices** [comment] 2022-01-26 11:01
Get issue in Chrome Windows 10: Versie 97.0.4692.99 (Officiële build) (64-bits)

**Comment by ProxiBlue** [comment] 2022-01-26 11:12
of interest, upgraded ubuntu chrome to .99, still works fine, so I will get a windows 10 vm up and have a test in a few days. It bugs me to not know why

**Comment by DHSServices** [comment] 2022-01-26 11:19
I wouldn't worry too much. I just realised it happens on hovering, which on a mobile device never is a problem. Just in our case with testing in a browser this is seen.
